enable_cache: False
extra:
  tags: experiment
settings:
  docker:
    required_integrations:
      - mlflow
steps:
  model_train:
    experiment_tracker: mlflow_tracker
  evaluation:
    experiment_tracker: mlflow_tracker